#!/usr/bin/env python3

### Copyright (c) 2020 Alex Chi
### 
### This software is released under the MIT License.
### https://opensource.org/licenses/MIT

from syscall import syscalls

print("""//! This file is automatically generated with `syscall.h.py`,
//! which contains all syscall ID.
""")

for (idx, syscall) in enumerate(syscalls):
    print(f"#define SYS_{syscall} {idx}")
