//! This file is automatically generated with `syscall.h.py`,
//! which contains all syscall ID.

#define SYS_fork 0
#define SYS_exit 1
#define SYS_wait 2
#define SYS_pipe 3
#define SYS_read 4
#define SYS_write 5
#define SYS_close 6
#define SYS_kill 7
#define SYS_exec 8
#define SYS_open 9
#define SYS_mknod 10
#define SYS_unlink 11
#define SYS_fstat 12
#define SYS_link 13
#define SYS_mkdir 14
#define SYS_chdir 15
#define SYS_dup 16
#define SYS_getpid 17
#define SYS_sbrk 18
#define SYS_sleep 19
#define SYS_uptime 20
